### PR TITLE
hatespeech

### PR DESCRIPTION
**Pull request by junaga**
you're a fucking idiot.

yep, this is hate without reason, but why are you a jerk without reason?

stop playing OSS, and start getting real. you're not fooling anybody. simply put: no one gives a fuck abt you.

### CODE REVIEW

**Comment by ljharb** [comment]
What exactly are you referring to?

**Comment by ljharb** [comment]
ah, it seems you might be referring to the core-js article, where the author misinterprets my comment as applying to him somehow?

**Comment by junaga** [comment]
not doing this, call junaga#8033, if you wanna talk

**Comment by ljharb** [comment]
That's not a phone number so I'm not sure what that means, but if you're willing to smear your own public credibility with this PR then I'm not sure why you wouldn't want to discuss it in public ¯\\\_(ツ)_/¯

**Comment by tj-commits** [comment]
STOP BEING MEAN TO LJHARB HE'S A FELLOW DEVELOPER YOU STUPID @junaga

**Pull request closed without merging**
